### ISSUE TITLE
OP: finality-provider: refactor and tests

### ISSUE THREAD

**Issue by bap2pecs** [babylonlabs-io/pm-integration#11]
**[<img src="https://avatars.githubusercontent.com/u/111917526?s=17&v=4" width="17" height="17"> @bap2pecs](https://github.com/bap2pecs)** cloned issue [babylonchain/pm-integration#1](https://github.com/babylonchain/pm-integration/issues/1) on 2024-07-09: 

## Refactor

- [x] remove unused `CommitPublicRandomnessResponse` and `SubmitFinalitySignatureResponse`

## Tests

- [x] split FP registration and starting the instances in op test manager
- [x] babylonchain/finality-provider#502
- [x] babylonchain/finality-provider#510
