### ISSUE TITLE
EPIC: OP finality contract

### ISSUE THREAD

**Issue by bap2pecs** [babylonlabs-io/pm-integration#12]
- [x] replace `query_grpc()` and `query_raw()` once `query_grpc()` is released by CosmWasm STD
- [x] https://github.com/babylonlabs-io/op-finality-gadget/issues/6
- [x] https://github.com/babylonlabs-io/babylon-contract/issues/82
- [x] https://github.com/babylonlabs-io/babylon-contract/issues/83
- [ ] ensure there is no gap at randomness submission
- [ ] ensure the finality provider is not slashed at EOTS submission
- [ ] ensure the finality provider has voting power / activated at EOTS submission
- [ ] allow configuring `min_pub_rand`
- [ ] babylonchain/babylon-contract#194
- [ ] babylonchain/babylon-contract#175 
- [ ] babylonchain/babylon-contract#157 
- [ ] babylonchain/babylon-contract#145
- [ ] babylonchain/babylon-contract#209
- [ ] babylonchain/babylon-contract#186
- [ ] babylonchain/babylon-contract#203
- [ ] babylonchain/babylon-contract#152 
- [ ] babylonchain/babylon-contract#208
