### ISSUE TITLE
EPIC: Optimism fork

### ISSUE THREAD

**Issue by bap2pecs** [babylonlabs-io/pm-integration#3]
## Summary

- [ ] https://github.com/ethereum-optimism/specs/discussions/218

## Tasks

- [ ] https://github.com/babylonlabs-io/optimism/issues/3 
- [ ] https://github.com/babylonlabs-io/optimism/issues/2
- [ ] https://github.com/babylonlabs-io/optimism/issues/9
- [ ] https://github.com/babylonlabs-io/optimism/issues/1
