### ISSUE TITLE
finality-provider: refactor, tests, fixes and chore

### ISSUE THREAD

**Issue by bap2pecs** [babylonlabs-io/pm-integration#5]
## Refactor

- [x] babylonchain/finality-provider#491
- [x] move a few test-only functions to tests e.g. `QueryFinalityProviders`

## Tests

- [x] babylonchain/finality-provider#403
- [x] babylonchain/finality-provider#487
- [x] babylonchain/finality-provider#449
- [x] babylonchain/finality-provider#439
- [x] babylonchain/finality-provider#415
- [x] babylonchain/finality-provider#414
- [x] babylonchain/finality-provider#397
- [x] babylonchain/finality-provider#346
- [x] babylonchain/finality-provider#345
- [x] babylonchain/finality-provider#343

## Fixes

- [x] babylonchain/finality-provider#478
- [x] babylonchain/finality-provider#463

> ## Chore

- [x] babylonchain/finality-provider#475
- [x] babylonchain/finality-provider#464
- [x] babylonchain/finality-provider#457
- [x] babylonchain/finality-provider#353
- [x] babylonchain/finality-provider#349

**Comment by SebastianElvis** [comment]
moved everything to https://github.com/babylonlabs-io/finality-provider/issues now 👍
