### ISSUE TITLE
EPIC: OP finality-provider

### ISSUE THREAD

**Issue by bap2pecs** [babylonlabs-io/pm-integration#8]
**[<img src="https://avatars.githubusercontent.com/u/111917526?s=17&v=4" width="17" height="17"> @bap2pecs](https://github.com/bap2pecs)** cloned issue [babylonchain/pm-integration#3](https://github.com/babylonchain/pm-integration/issues/3) on 2024-06-20: 

- [x] babylonchain/finality-provider#497
- [x] fix flaky test `TestOpMultipleFinalityProviders` (see babylonchain/finality-provider#509)
- [x] babylonchain/finality-provider#498  
- [x] babylonchain/finality-provider#496
- [x] babylonchain/finality-provider#432 
- [x] babylonchain/finality-provider#508
- [x] babylonchain/finality-provider#528
- [x] babylonchain/finality-provider#529
- [x] https://github.com/babylonlabs-io/finality-provider/issues/72
